laravel/installer

- src/NewCommand.php
When installing via Composer, it automatically duplicates the .env.example file. Now the Laravel installer does too.
This addition has been tested.
> Duplicate .env.example for new apps.

- zipper.sh
The files in ```vendor/bin``` or symbolic linked.
Use the -y  for ```zip``` will keep the symbolic links.
Otherwise this will produce an error:
```sh
php laravel new test-app
cd test-app/vendor/bin
php ./phpunit
```
> Keep symbolic links in zip

- src/NewCommand.php
If you run the installer to create a new project it says the
Application key was set successfully even though it wasn't.
This calls the composer script to copy .env.example to .env, so the
next script that calls artisan key:generate will work.
The reason for the current behavior is that php artisan key:generate
doesn't display an error if it fails to find a .env file.
> Call composer command to copy .env file

- src/NewCommand.php
Before this fix, creating a new application throws a fatal error if the Zip extension is not installed.
> Throw an exception instead of a fatal error for the Zip extension.

- src/NewCommand.php
Currently there is only checks for if a directory exists with that name, however, we don't check whether a file exists with the name. If it does, then you get a ZipArchive error:
> Throw error if a file exists with that name

- src/NewCommand.php
Makes laravel  `--no-ansi` be respected, even when showing the result of the composer command.
> Respect --no-ansi option

- composer.json
If the Zip PHP extension is not installed, create a new project its impossible, the use of this module its useless... should be require...
> require zip extension

- src/NewCommand.php
When you already have an existing directory under source control and want to install laravel to it, it can be a little bit tedious since the installer wont write to an existing directory.
To handle this use case, a --force option is provided which ignores if the directory already exists and proceeds to install to that directory.
> Add --force option to ignore existing directory in new command

- composer.json
- src/NewCommand.php
I find my self having to manually set the permissions on the `storage` and `bootstrap/cache` folders after each new install. Would be nice if it the installer at least attempts to do this automatically and gives a nice reminder if it can't. My first Laravel PR
Huge fan.
> Set permissions for directories that need to be writable by server

- src/NewCommand.php
Unless I'm missing something obvious there should be no need to run `post-autoload-dump` a second time for dev.
> Remove duplicated command

- src/NewCommand.php
The other available commands and general output don't include a final full stop, only this one does.
I know it's not a big deal but just spotted it this morning. For reference it's probably worth pointing out the all the built-in commands with a fresh Laravel app omit the final full stop as well.
> Remove final full stop to make description consistent

- src/NewCommand.php
The usage info for the installer says that the `--quiet` option can be used to prevent if from outputting things:
```
Usage:
new [options] [--] [<name>]
Arguments:
name
Options:
[...]
-q, --quiet           Do not output any message
[...]
```
However, this option is not honored, because it is never passed to Composer.
Similarly to what has been done in #52 for `--no-ansi`, this PR ensures that Composer is made aware of this option.
I’m using the Laravel installer as part as a script, to automate the creation of Laravel projects and tweak additional things. I would like to prevent the installer from outputting anything, so that its messages do not interfere with the ones coming from my script.
> Respect --quiet option

- src/NewCommand.php
Reopen PR #85.
- Update the composer execution path on `NewCommand::findComposer` command.
Actually, the original `php compoer.phar` string result is not correct.
And this will not specify the current path to let PHP binary know where the `composer.phar` can execute.
It should use the current `composer` path to tell PHP binary to execute `composer.phar`.
- Ubuntu 18.04
- composer version is `1.8.4`.
Here are steps about reproducing the issue.
- Firstly, we use the `composer require laravel/installer` command.
- Then using the `vendor/bin/laravel new blog` to create the new Laravel project.
- It will get the error message in following image during building the Laravel project.
> Update composer path on findComposer

- src/NewCommand.php
If you want to create a new laravel project in an existing directory, you have to use `laravel new` (without a path). If you try using `laravel new .`, like you would with most command line utilities, you get an error "Application already exists!".
This PR makes it possible to create a new laravel project in the current directory using `laravel new .`
> Create a new project in the current directory using "laravel new ."

- src/NewCommand.php
The `laravel new` command was consistently failing for me. My corporate firewall was scanning the ZIP before it would let the download continue, so what was immediately returned was not a ZIP. The extract was failing because of that.
Someone else on StackOverflow was having the same problem [here](https://stackoverflow.com/a/47392640).
> Make sure zip file is valid before extracting

- .gitattributes
- .gitignore
- .travis.yml
- bin/laravel
- composer.json
- phpunit.xml.dist
- src/NewCommand.php
- tests-output/.gitignore
- tests/NewCommandTest.php
This PR updates the installer with a couple of things:
- Provides Symfony 5.x support
- Drops Symfony 3.x
- Minimum PHP version is now 7.2 as the framework (since you can't use the installer on anything lower anyway)
- Added an integration test for the command
- Added a Travis build file for testing in multiple PHP environments
- Moved the laravel binary to the more sensible default `/bin` folder just like Envoy
- Fixed a bug with improper string passing to the Process constructor
This will need to be released as a new major release.
> [3.x] Prepare 3.0 release

- composer.json
`NewCommand` relies on `Process::fromShellCommandline()`, which was introduced in `symfony/process` version [4.2.0](https://github.com/symfony/process/commit/d6f417d21efe2a2b91c0c8a19d938c5db18d81d3).
> require symfony/process 4.2

- composer.json
- src/NewCommand.php
- tests/NewCommandTest.php
> Switch to using composer create-project

- tests/NewCommandTest.php
- Using the `assertSame` to replace `assertEquals` and it can make assertion equals strict.
- According to the official [PHPUnit doc](https://phpunit.readthedocs.io/en/9.0/assertions.html#assertsame), the `assertSame` parameters are `assertSame(mixed $expected, mixed $actual[, string $message = ''])`.
And parameters should be switched.
> Using the assertSame and fix assertSame parameters

- composer.json
- src/NewCommand.php
- According to this [line](https://github.com/laravel/installer/blob/master/src/NewCommand.php#L72) of `src/NewCommand` class and the [line](https://github.com/laravel/installer/blob/master/.github/workflows/tests.yml#L16) of `.github/workflows/tests.yml` file,  it should let this installer require `php-7.3` version at least on `composer.json` file.
> [4.x] The Laravel Installer requires PHP-7.3 at least

- src/NewCommand.php
- tests/NewCommandTest.php
Had a fresh install blow up today 😅 This PR:
- Wraps $directory passed to (non-Windows) shell commands in quotes
- Returns the process exit code so the test can catch a similar issue in the future
- Applies the same quote wrapping to the test clean up shell command
> Fix for directories with spaces in current working directory path

- src/NewCommand.php
Re #129 
@driesvints I ended up using the throwing an exception as [that's what the current code does](https://github.com/laravel/installer/blob/master/src/NewCommand.php#L180) if you don't use `--force` and the directory already exists as there is no `->error(...)` method as we're using the base symfony command rather than Laravels extended commands.
**--force and current directory**
**without --force and directory already exists**
> [4.x] Add warning about --force and installing in current directory

- src/NewCommand.php
Alter command to `755` artisan when a new laravel application is created. I can't see a reason why not, and it would give me one less thing to do when I create new laravel applications! 😎
> Ensure artisan command is executable (755)

- src/NewCommand.php
At the moment running `laravel new orion` only update `DB_DATABASE=orion` on `.env` and not `.env.example`. But I think it might be useful if `.env.example` should be updated as well since this is only used once by the repository manager/project manager.
> Would be useful if DB_DATABASE is updated on the .env.example as well

- .github/workflows/tests.yml
`league/flysystem` requires `fileinfo`
> [4.x] PHP 8 Support Windows

- src/NewCommand.php
This PR adds git support to the Laravel installer. It'll allow users to immediately set up a Git repository with a fresh Laravel app committed into the Git history. Additionally, when using the `--github` flag, the installer will use [GitHub's `gh` CLI tool](https://cli.github.com) under the hood to push the project to a private GitHub repo under the user's GitHub account. This'll make getting up an running with a new Laravel project that more easier.
Set up a new Laravel project and initialize a repo with the base skeleton committed:
```bash
laravel new my-app.com --git
```
The same as above but also automatically create a private GitHub repository:
```bash
laravel new my-app.com --github
```
The repo will then be available at `github.com/<your-account/my-app.com`.
The same as above but …
> Git support

- src/NewCommand.php
After talking to some of my GitHub contacts they gave me a tip for a safer way to do a `git push` after creating the GitHub repo. Doing so will allow us to remove the note about the `gh_protocol` in the docs as it won't matter anymore what protocol you use.
> Improve Git push

- src/NewCommand.php
Apparently I completely misunderstood the usage of `--team` and therefor it's currently impossible to create a GitHub repo under an organisation. I've therefor added a new `--organisation` flag that can be used to create the repo under a specific GitHub organisation. 
After this PR is merged I'll update the blog post and docs.
> Add organisation flag

- src/NewCommand.php
This should fix the git protocol issue and make sure the command works on Windows by passing the env variable properly to the Symfony console process. Thanks to @owenvoke & @mislav.
> Update pushing branch

- src/NewCommand.php
@driesvints As discussed on twitter, this is a simple PR that hopefully follows your coding standards. This PR allows a user to use a different branch name, than the hard coded "main" branch.
I would have liked to use the default branch name as configured by git config as a fallback before reverting to "main". You would get this via the following command - `git config --global init.defaultBranch`. However, I wasn't sure how best to implement this.
> Add the ability to change the branch name from "main"

- src/NewCommand.php
This PR will add support for git version less than 2.28.0. Which is the only version that has the `-b` option for creating a repo during the initialization.
This will help Linux users which is by default to have Git version less than 2.28.0.
> Add support for oldest versions of Git

- src/NewCommand.php
- Fixes the `laravel new` command failing without the `no-ansi` option
---
The underlying Symfony `Input::getOption` ([source](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Console/Input/Input.php#L150)) fails when the option is missing in the command definition, so I think we need to call it after a `$input->hasOption()` check. Not sure how this has been working before (as it looks like things haven't changed in a while both in Symfony console and here), but it broke today on my end when running `laravel new ...`.
Running the tests was also failing over here and I enabled the workflows on my fork repository to [show it breaking](https://github.com/tonysm/installer/actions/runs/894362202). I was getting the same error locally:
I'm not sure about the other `getOption` …
> Fix new command failing without no-ansi option

- src/NewCommand.php
This PR fixes the previous `no-ansi` breakage by making use of the `isDecorated` method on the Symfony output to make sure that no output is colorized when the `no-ansi` flag is passed.
See https://github.com/symfony/symfony/pull/39642#issuecomment-852006010
> Use isDecorated for no-ansi detection

- src/NewCommand.php
Git provides a global configuration to override the default branch when a new repository is initialized.
Even though laravel/installer provides a way to override the default branch name, laravel/installer does respect git global configurations.
[init.defaultBranch:- Allows overriding the default branch name e.g. when initializing a new repository.](https://git-scm.com/docs/git-config#Documentation/git-config.txt-initdefaultBranch)
> Respect git global config for a default branch

- src/NewCommand.php
On Windows OS when using the `--force` option and the directory does not exist it will throw an error "The system cannot find the file specified.".
This PR ensures the directory exists before deleting.
Tested on Windows 10 Pro Version 10.0.19044 Build 19044
> Check directory before deleting in Windows OS

- src/NewCommand.php
GitHub has added a new `--push` flag which simplifies the process of pushing the HEAD branch to the newly created repo.
See https://github.com/cli/cli/issues/3209#issuecomment-1161572256
> Simplify push to GitHub

- src/NewCommand.php
Although domain names are case-insensitive, browsers rewrite domains to all lowercase.
This PR aims to match this behaviour.
> Changes APP_URL replacement with name to lower

- src/NewCommand.php
This PR fixes an issue where the installer will generate a `*.test` hostname that is unresolvable on many machines.
If the user has not installed Valet (which doesn't exist for Windows and Linux), then the `*.test` hostnames will not resolve unless they have manually set up their DNS to handle it.
This PR solves that by testing whether the `*.test` hostname resolves before using it, otherwise it leaves the `APP_URL` as `http://localhost`.
This is especially useful with Vite, as we output the `APP_URL` to the console to guide users away from visiting the Vite dev server URL directly.
> Prevent unresolvable `APP_URL`

- src/NewCommand.php
If https://github.com/laravel/jetstream/pull/1119 is merged, then this installer will no longer need to run the `npm install` and `npm run build` commands as they will be handled by the Jetstream installer instead.
> Remove duplicate `npm install` and `npm run build` steps

- src/NewCommand.php
There is a PR at https://github.com/laravel/jetstream/pull/1133 to run this command via the Jetstream installer instead so that it is run regardless of what method is used to install Jetstream.
> Remove `storage:link` command

- src/NewCommand.php
This pull request adds Laravel Breeze scaffolding to the `laravel new` command, and it looks like this:
> [4.x] Adds Laravel Breeze scaffolding

- src/NewCommand.php
If you try to run the `laravel new --jet` command without the capability to use the interactive form, you will get an error that the testing framework is not provided. Also, adding this a mirror to the `--pest` flag. Since this is the default behavior, adding the `--pest` flag will result in the pest framework being selected.
> Add an option to install PHPUnit

- src/NewCommand.php
Jetstream now also supports the "dark" option. Installer should pass this parameter.
> [4.x] Adds option "dark" to jetstream installation

- src/NewCommand.php
When running the `laravel new` command in certain environments, unsupported options are added to git commands.
This PR fixes that issue by excluding them just like was already done for `chmod`.
> Prevent unknown option with git commands

- src/NewCommand.php
- stubs/pest/Unit.php
This pull request makes the installer start using Pest v2.
> [4.x] Uses Pest v2

- src/NewCommand.php
This PR wraps all PHP_BINARY commands in quotes, to avoid any issues that could occur in case the PHP binary is in a folder containing spaces.
> Wrap PHP_BINARY in quotes

- src/NewCommand.php
If you run `laravel new example-app --github` you are still getting asked if you want to initialize a Git Repository.
This PR removes the prompt if the Option `--github` is found.
> Don't prompt for Git if Github Option is found

- src/NewCommand.php
This PR updates the final output of the installer to include the chosen directory name:
This might not be an issue for most, but I often forget the directory name I chose, especially if I switched away while the installer runs.
The Vue installer does something similar (including the name twice), but I opted not to provide the `cd` instruction because it looked a little weird on its own (we don't need to tell them to `composer install`) and developers may want to open the directory in their editor instead of "cd-ing".
I also wondered whether it could be worth adding some "Next Steps" including links to the docs on running development servers and using starter kits. Thoughts?
> Show the directory name at the end of the installer

- src/NewCommand.php
Add an option to indicate whether Breeze should be scaffolded with TypeScript support.
> add option to indicate whether Breeze should be scaffolded with TypeScript support

- src/NewCommand.php
This pull request does two things:
1. Sorts the options being displayed when using the `--help` option, so it gets a little bit more organized:
2. Adds missing jetstream options `--api` and `--verification`:
> [5.x] Adds missing jetstream options

- src/NewCommand.php
* Allow selecting `sqlite`, `mysql` or `pgsql` driver using Laravel Prompts
* Default to `mysql` if accessed via `--no-interaction`.
* Update `DB_CONNECTION` to the correct database driver. (SQLite database doesn't update `.env.example`)
* Comment other `DB_*` variables when using `sqlite`.
* Update `DB_PORT` value based on selected database driver.
> Add ability to select default database connection

- src/NewCommand.php
This PR fixes an issue where Jetstream SSR support is not installed when using either the `--ssr` option or the "Inertia SSR" option in the prompts.
> Fix Jetstream SSR option

- src/NewCommand.php
This PR adds the newly added livewire stack option to the installer
> Add the Livewire stack

- src/NewCommand.php
When creating a new Laravel project using the installer, and selecting sqlite as database the .env file `DB_DATABASE` row ends up being commented out twice:
```
```
This PR fixes that by removing the extra line in `$defaults`
> Remove extra DB_DATABASE

- src/NewCommand.php
- It should be good to use the `str_starts_with` function to check the specific first sub-string.
- According to the [reference](https://www.php.net/manual/en/function.str-starts-with.php), the feature is available since the PHP 8 version is released.
> Apply using the str_starts_with function

- src/NewCommand.php
Laravel 11 will support a new Maria DB Configuration in `config/database.php` (due to slimming the skeleton this will be moved to the framework).
A developer should be able to select the option `mariadb` during installation. Which will fallback to `mysql` in Laravel 10 and will use the `mariadb` configuration in Laravel 11.
~Note: This PR will be draft until the slimmed skeleton is merged. Because the Slimmed skeleton branch is not working, I can not verify if everything works as intended.~
Works on the master branch and the 10.x branch
Tested as follows:
Replace the file in `~/.composer/vendor/laravel/installer/src/NewCommand.php`
Run `laravel new l11 --dev` and select database mariadb => `.env` should contain mariadb
Run `laravel new l10` and select database mariadb => `.env` should …
> Add mariadb installation option

- .github/workflows/tests.yml
- composer.json
- phpunit.xml.dist
- src/NewCommand.php
This pull request adds Laravel 11 support to the installer.
> [develop] Adds Laravel 11 support

- src/NewCommand.php
This pull request aims to enhance the Laravel installer by introducing default values for selection questions during the process of creating a new application. The addition of default values streamlines the installation process, making it more user-friendly and efficient.
With this update, I've implemented default values for certain selection questions that users encounter while creating a new Laravel application. These defaults are thoughtfully chosen to align with best practices and common preferences, ensuring a smoother on-boarding experience for both new and experienced users.
By providing default values, users can simply accept the pre-filled options if they align with their requirements. This significantly reduces the number of manual inputs, making the installation process faster …
> [5.x] Added default value on selection question while creating new application

- .github/workflows/tests.yml
- composer.json
This pull request allows the usage of Symfony 6 components while keeping supporting Symfony 7 components.
> [develop] Keeps supporting older illuminate components

- src/NewCommand.php
This pull request improves the installation output of Pest - previously, the Tty was not being used, causing the composer's output to lack colors - while executing the `composer require pestphp/pest` command.
> [5.x] Improves installation of Pest

- src/NewCommand.php
Fixes https://github.com/laravel/installer/issues/313.
This pull request fixes the usage of the caret (^) as that char is not supported on Windows shells. The fix is simply not be explicit about the version, as we don't even need to be explicit.
> [5.x] Fixes Pest installation on Windows

- src/NewCommand.php
The configuration files are published by default.
> [11.x] Removes `publish config` files

- src/NewCommand.php
This `$migrate` parameter is not used in the `configureDefaultDatabaseConnection` function.
> Remove unused `migrate` parameter

- src/NewCommand.php
Adds a `--database` option to select the database when running in non-interactive mode.
> Add `--database` option

- src/NewCommand.php
This pull request removes the "experimental" of Breeze's TypeScript stack.
> [5.x] Removes "(experimental)" label

- src/NewCommand.php
Breeze is actually recommended to be installed as a dev dependency because it only scaffolds files. Ideally we'd also remove the dependency again after scaffolding Breeze.
https://laravel.com/docs/11.x/starter-kits#laravel-breeze-installation
See https://github.com/laravel/installer/issues/331
> Install Breeze with dev flag

- .github/workflows/tests.yml
- src/NewCommand.php
~This PR will make sure that unavailable database options are filtered out of the database list. In some rare situations, Sqlite isn't available and people fail their installations because they press continue on it as the default. This PR will filter out Sqlite when it's not available as a PDO driver and will move to the next in line as the default. Similar, SqlServer is filtered out on macOS, etc.~
Pending https://github.com/shivammathur/setup-php/discussions/835
> Prevent using unavailable databases

- src/NewCommand.php
Hey 👋,
This PR checks if the current location is parked with Herd or Valet, and shows this output:
Instead of:
```sh
php artisan serve
```
Thanks
> Improves output if Herd or Valet are installed.

- src/NewCommand.php
`composer.json` from `laravel/laravel` will create `database/database.sqlite` and run `php artisan migrate` before we even select the default database.
1. Disable scripts during `composer create-project` to avoid above scenario.
2. Run `composer run post-root-package-install` to copy `.env.example` to `.env`.
3. Run `php artisan key:generate`
4. Select the correct database using prompt.
5. Run migration
https://github.com/laravel/installer/assets/172966/443d4447-8ebc-474f-9f52-2d5adc00cb5d
> Only run migration after selecting the database

- src/NewCommand.php
This PR fixes a bug when running the installer with the `--quiet` option.
The `-v` enforces the output so that error should not happen anymore.
Thanks
> [1.x] Enforce output when running with `--quiet`

- src/NewCommand.php
This PR fixes the issue #342.
I could not replicate on my machine but based on the error information provided by @Anticom, catching the `ProcessStartFailedException` it should solve.
Cheers.
> [5.x] Fixes issue if there is no `herd` or `valet` installed

- src/NewCommand.php
Solves when the directory already exists, it still asks a couple of questions before showing the error message
> Validate Laravel can be installed on selected directory

- src/NewCommand.php
Since we now run `composer create-project` with `--no-scripts` the command should run migration when `--database` option is available.
fixes #345
> Automatically run migration when `--database` is given.

- src/NewCommand.php
Fixes https://github.com/laravel/installer/issues/352
This prompt comes from the `migrate` command, and [by the looks of that](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Database/Console/Migrations/MigrateCommand.php#L196) the only way to ensure the SQLite file is created without a prompt is to add `--force`. Adding `--no-interaction` to `migrate` results in no file being created, which then errors when the migrations run.
Hopefully this is OK but let me know if you'd like any changes.
> Fix `--no-interaction` SQLite file prompt

- src/NewCommand.php
This PR brings the new `eslint` option for the Breeze Inertia stack. https://github.com/laravel/breeze/pull/412
> [5.x] Add `eslint` option for breeze inertia stack

- src/NewCommand.php
This PR replaces the original development environment setup instruction: `php artisan serve` with the newly provided `composer run dev`.
> Replace `php artisan serve` with `composer run dev`

- src/NewCommand.php
> [5.x] Remove `php artisan pail` from `composer run dev` on Windows 

- src/NewCommand.php
- tests/NewCommandTest.php
This PR addresses two, minor issues.
First, due to a logic bug when testing for Herd or Valet, a default `.test` extension could never be reached. This ultimately leads to `APP_URL` always being `http://localhost` instead of a potentially valid `http://app-name.test`.
Second, if a developer appends a trailing slash to the name everything is installed and the application runs. However, all tests will fail until the developer realizes the `APP_URL` was set to `http://app-name/.test`. While an arguably an incorrect use case, it's a pretty easy fix to avoid such an annoying experience.
> Remove any trailing slash from application name

- src/Concerns/InteractsWithHerdOrValet.php
- src/NewCommand.php
- tests/NewCommandTest.php
* Move `herd` and `valet` related code to `Laravel\Installer\Console\Concerns\InteractsWithHerdOrValet`
* Skipped `test_it_can_chops_trailing_slash_from_name` when `valet` or `herd` is missing.
> Test Improvements

- composer.json
Fixes #375
Please let me know if I should include further details, this is my first time contributing to anything in the Laravel ecosystem :smile:
> Ensure Symfony/mbstring-polyfill version 1.31 or higher

- src/NewCommand.php
- tests/NewCommandTest.php
Resolves #384 
The missing `mb_trim()` function causes `laravel new` to crash on Windows WSL when running a PHP version lower than 8.4.
Considering the command isn't being used to strip multi-byte characters, `rtrim` should work fine and won't lead to any issues for users who are not yet on PHP 8.4.
> Fix Laravel installer on Windows WSL

- src/NewCommand.php
No need to have drfit plugin once the tests were migrated to pest
> Remove drift plugin after running drift command

- src/NewCommand.php
This PR fixes an issue when using the current version of the Laravel installer in a non-interactive command.
Right now, the installer always shows a confirmation prompt asking if the user wants to install the NPM dependencies.
This is a problem when running the installer in a non-interactive way, for example:
```
laravel new no-interaction -n
```
This PR changes this behaviour. If the installer is running in non-interactive mode, the NPM dependencies only get installed when the new `--npm` option gets passed to it.
For example:
```
laravel new no-interaction -n --npm
```
> Add npm option to fix no-interaction installs

- src/NewCommand.php
- With these changes, we may allow the installation of custom starter kits by passing the `--starter-kit` option.
---
Context: I'm working on a Hotwired Starter Kit and I thought it would be cool if we could create a Laravel app using the official installer but passing a custom starter kit. For instance:
```bash
laravel new --starter-kit=hotwired-laravel/turbo-starter-kit turbo-chirper
```
> [12.x] Adds an option to install a custom starter kits

- src/NewCommand.php
- When it runs the pest installation function, all files in the application's directory will be opened so it removes the `uses(RefreshDatabase::class)` line. But it only needs to open the test files for that.
---
Context: I am working on the [Hotwire Starter Kit](https://github.com/hotwired-laravel/hotwire-starter-kit) and it comes with the [Tailwind CSS Laravel](https://github.com/tonysm/tailwindcss-laravel), which downloads the Tailwind CLI binary, so the installer was dying due to exhausted memory.
> [5.x] Only open files in the tests directory when converting to Pest

- src/NewCommand.php
SQLite will be used regardless of using the `--database` option
```bash
laravel new sk-3 --database pgsql
``` 
It should use the desired database driver
```bash
laravel new sk-1 --database pgsql
```
It validates invalid driver names
```bash
laravel new sk-2 --database invalid-driver-name
```
> fix: Starter kits should not ignore the `--database` option

- src/NewCommand.php
**Don't pass --no-ansi to rm**
When --force is used, rm is part of $commands.
rm something --no-ansi succeeds on macOS but fails on Linux.
---
**Properly check if output is a TTY**
This now matches the check setTty() does.
Previously we were only checking the directory separator
and that /dev/tty exists and is readable.
isTtySupported() checks if /dev/tty is *writable* and more
importantly that STDOUT itself is a TTY.
Simply running `laravel new --stuff foo | head` would produce TTY warns
on systems where /dev/tty exists just fine and only stdout is piped.
> Don't pass --no-ansi to rm, properly check if output is a TTY

- src/NewCommand.php
This PR checks for any newer versions of the installer on Packagist and offers to self-update for the user if one exists. 
It only checks Packagist at most once per 24 hours, and sends the `If-Modified-Since` header for maximum caching.
> Check for new version of installer on `new`

- src/NewCommand.php
Hi. I've make this addition to the installer in order to be able to use bun runtime to install/build packages. I've also added a new variable to manage the build command.
> feat: bun package install/build
