laravel/installer

- composer.json
- laravel
- src/NewCommand.php
How do these looks instead? I assume you were against the docblock changes I made before.
> New CS Fixes

- src/NewCommand.php
- zipper.sh
> ET minor fixes

- src/NewCommand.php
> Revert "Parameters removed because they are not in use"

- composer.json
- composer.lock
I've tested it on my homestead and a windows 10 machine.
> Allow use of Guzzle 6.0

- composer.json
Note that the lock file needs updating.
> Allow global installs along side symfony 3 deps

- src/NewCommand.php
This allows us to get the coloured output from Process.
> Allow TTY output from process

- src/NewCommand.php
This just fixes the phpdocs and type hinting for `getVersion()` method.
🌵
> Fix PHP docs

- src/NewCommand.php
GET "http://cabinet.laravel.com/latest-52.zip" resulted in a 404 Not Found response.
> 5.2 option flag doesn't work anymore.

- src/NewCommand.php
Hi,
It always bugs i can't do `laravel new -f` but i have to `laravel new --force`. This pull request adds the option to use the `-f` alias.
> Added an alias to the force option

- src/NewCommand.php
Don't tell the user to `...build something amazing` if the installation fails 😄
> Check installation was successful

- .github/workflows/tests.yml
- src/NewCommand.php
Closes https://github.com/laravel/installer/issues/117
> Drop support for PHP 7.2

- .github/workflows/tests.yml
- .gitignore
- src/NewCommand.php
- tests/NewCommandTest.php
This is an extension of #131 which fixes #128.
This PR also prevents running chmod on Windows (which would equally fail) and only executes the removal of a directory if the `--force`  option has been passed. It also adds tests for for Windows.
> [4.x] Fix multiple issues when running on Windows.

- src/NewCommand.php
> [4.x] Fix issues when running on Windows. (#136 and #129)

- src/NewCommand.php
Fixes https://github.com/laravel/installer/issues/154
> [4.x] Fix quiet and no-ansi flags

- README.md
Shields.io works a lot better than the old pugx.org.
> [4.x] Update the badges to use shields.io

- src/NewCommand.php
This will make the name argument a required one.
> [4.x] Require name argument

- src/NewCommand.php
> Fix option calls

- src/NewCommand.php
> Revert "Improve Git push"

- src/NewCommand.php
> Return type

- composer.json
> Symfony v6

- src/NewCommand.php
Flag --confirm / -y has been deprecated, passing any argument skips confirmation prompt.
> Maintain current functionality with gh repo create rewrite

- src/NewCommand.php
This fixes support for the new Vite pipeline.
> Use build command instead of dev command

- src/NewCommand.php
This pull request makes the output of the installer similar to the framework:
> [4.x] Improves console output

- src/NewCommand.php
This pull request fixes the installation of Pest in Laravel 10.
> [4.x] Fixes installation of Pest in Laravel 10

- .gitattributes
- .github/workflows/static-analysis.yml
- composer.json
- phpstan.neon.dist
This pull request adds type checking to this repository.
> [4.x] Adds type checking

- src/NewCommand.php
> Fixes breeze installation with `--ssr` options

- CHANGELOG.md
- composer.json
- src/NewCommand.php
* Continue and replace #273 PR
* Use new helper methods from laravel/framework#48096
* Use `Process` `$cwd` variable to run command from path instead of using `chdir()`
> Updated to use the Process constructor to install Pest and use `Composer` helper class

- src/NewCommand.php
This pull request adjusts the installer options on what concerns Laravel Breeze.
> [5.x] Adjusts new command with new Breeze options

- composer.json
This pull request fixes the `composer.json` alias.
> [5.x] Removes alias

- README.md
Goes hand in hand with https://github.com/laravel/docs/pull/9232
Fixes https://github.com/laravel/installer/issues/296
> Adjust link to docs

- src/NewCommand.php
This PR checks if `herd` or `valet` are installed.
if so it will check check for the "tld" used, if there is none it will default to "test" as it was before.
Thanks.
> Gets the default "tld" on install.

- src/NewCommand.php
This would improves installation on Laravel Herd
> [5.x] Utilise `Illuminate\Support\php_binary()`

- composer.json
> [5.x] Support Laravel Prompts 0.2+ and 0.3+

- .github/workflows/tests.yml
- src/NewCommand.php
> [5.x] Supports PHP 8.4

- bin/laravel
> Update version to 5.11.1

- .github/workflows/tests.yml
- src/NewCommand.php
fixes https://github.com/laravel/installer/issues/395
`vendor/bin/pest` doesn't have `--no-ansi` and `--quite` options.
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>
> Fix Pest installation

- composer.json
> Use PHPStan 2

- src/NewCommand.php
Updated from https://github.com/laravel/installer/pull/400
> Use pest command in github workflow when using pest
